### PR TITLE
Create Selection Sort

### PR DESCRIPTION
**Pull request by shreyraj2002**
Selection Sort in Java

### CODE REVIEW

**Comment by imhardikdesai** [comment]
Use proper extensions for file
 .java for java file

**Comment by shreyraj2002** [comment]
Changes done

**Comment by imhardikdesai** [comment]
I Will Merge Your PR Soon , with `hactoberfest` Label

**Comment by shreyraj2002** [comment]
Thanks can I add more algos here?

**Comment by imhardikdesai** [comment]
Of course also you can tell your friends too. Ensure that the algorithm file is not exist in Repository.

**Comment by shreyraj2002** [comment]
hi as I can see the maintainer has to mark the contribution with HACKTOBERFEST-ACCEPTED label pls mark that

**Pull request merged**
