### PR TITLE
Create insertionsort.cpp

### PR DESCRIPTION
**Pull request by arshya-garg**

### CODE REVIEW

**Comment by imhardikdesai** [comment]
Merge_sort is already exists in C Programs Folder

**Comment by arshya-garg** [comment]
ohh .. I didn't saw it

**Comment by arshya-garg** [comment]
Please can you merge Insertion sort and merge sort in cpp folder.

**Comment by imhardikdesai** [comment]
Okay, I have deleted C Program file and merged remaining Files

**Pull request merged**
