### PR TITLE
hacktoberfest-2022

### PR DESCRIPTION
**Pull request by up2002**
Please add my file in your repository with hacktoberfest.

### CODE REVIEW

**Comment by imhardikdesai** [comment]
add file wit proper Extensions

example:- .cpp for C++

**Comment by up2002** [comment]
Boyer Moore's Voting Algorithms

**Review by up2002 — COMMENTED** [review]
Boyer Moore's Voting Algorithms

**Comment by imhardikdesai** [comment]
I Will Merge Your PR Soon , with `hactoberfest` and `hactoberfest-accepted` Label

**Pull request merged**
